spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/mp_ticket?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&verifyServerCertificate=false&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 810156
#mybatis
mybatis-plus:
  #mapper文件
  mapper-locations: classpath:mapper/*.xml
  #实体文件
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: cn.syjava.ticket.client.entity.*
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
  #mybatis原生配置
  configuration:
    #驼峰下划线转换
    map-underscore-to-camel-case: true
    #不开启二级缓存
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root:  ERROR
    org.springframework:  ERROR
    org.mybatis:  ERROR
    org.syjava.ticket.db:  DEBUG

feign:
  #开启okhttp
  okhttp:
    enabled: true
  #开启hystrix
  hystrix:
    enabled: true
  httpclient:
    max-connections: 1000
  #配置对请求内容的压缩
  compression:
    request:
      enabled: true
      min-request-size: 16
    response.enabled: true

#security:
#  oauth2:
#   resource:
#      user-info-uri: http://localhost:7777/oauth/user
#      prefer-token-info: false
#      jwt:
#        key-uri: http://localhost:7777/oauth/token_key
