sp:
  user-service:
    users: "[{\"id\":10, \"username\":\"abc\",\"password\":\"123\"},{\"id\":12, \"username\":\"def\",\"password\":\"456\"},{\"id\":9, \"username\":\"ghi\",\"password\":\"789\"},{\"id\":100, \"username\":\"hs\",\"password\":\"123456\"}]"

spring:
  application:
    name: user-service
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
management:
  endpoints:
    web:
      exposure:
        include: refresh
    
server:
  port: 8101
